// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: server/v1/databases.proto

package serverv1

import (
	v1 "github.com/deeploop-ai/fleet/genproto/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseRequest) Reset() {
	*x = CreateDatabaseRequest{}
	mi := &file_server_v1_databases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseRequest) ProtoMessage() {}

func (x *CreateDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseRequest.ProtoReflect.Descriptor instead.
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDatabaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseRequest) Reset() {
	*x = GetDatabaseRequest{}
	mi := &file_server_v1_databases_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseRequest) ProtoMessage() {}

func (x *GetDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseRequest.ProtoReflect.Descriptor instead.
func (*GetDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{1}
}

func (x *GetDatabaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDatabasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Databases     []*Database            `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesResponse) Reset() {
	*x = ListDatabasesResponse{}
	mi := &file_server_v1_databases_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesResponse) ProtoMessage() {}

func (x *ListDatabasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesResponse.ProtoReflect.Descriptor instead.
func (*ListDatabasesResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{2}
}

func (x *ListDatabasesResponse) GetDatabases() []*Database {
	if x != nil {
		return x.Databases
	}
	return nil
}

func (x *ListDatabasesResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_server_v1_databases_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{3}
}

func (x *Database) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Database) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Database) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Database) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_server_v1_databases_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCollectionRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *CreateCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Queries       []string               `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_server_v1_databases_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{5}
}

func (x *ListCollectionsRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *ListCollectionsRequest) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *ListCollectionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCollectionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_server_v1_databases_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{6}
}

func (x *GetCollectionRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *GetCollectionRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*Collection          `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_server_v1_databases_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{7}
}

func (x *ListCollectionsResponse) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *ListCollectionsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,2,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Attributes    []*Attribute           `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Indexes       []*Index               `protobuf:"bytes,6,rep,name=indexes,proto3" json:"indexes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_server_v1_databases_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{8}
}

func (x *Collection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Collection) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *Collection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collection) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Collection) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Collection) GetIndexes() []*Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *Collection) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Collection) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Size          int32                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Required      bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	Array         bool                   `protobuf:"varint,7,opt,name=array,proto3" json:"array,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,8,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttributeRequest) Reset() {
	*x = CreateAttributeRequest{}
	mi := &file_server_v1_databases_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttributeRequest) ProtoMessage() {}

func (x *CreateAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttributeRequest.ProtoReflect.Descriptor instead.
func (*CreateAttributeRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAttributeRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *CreateAttributeRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *CreateAttributeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateAttributeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateAttributeRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CreateAttributeRequest) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *CreateAttributeRequest) GetArray() bool {
	if x != nil {
		return x.Array
	}
	return false
}

func (x *CreateAttributeRequest) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Array         bool                   `protobuf:"varint,6,opt,name=array,proto3" json:"array,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_server_v1_databases_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{10}
}

func (x *Attribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Attribute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Attribute) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attribute) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Attribute) GetArray() bool {
	if x != nil {
		return x.Array
	}
	return false
}

func (x *Attribute) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

type CreateIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Attributes    []string               `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Orders        []string               `protobuf:"bytes,6,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexRequest) Reset() {
	*x = CreateIndexRequest{}
	mi := &file_server_v1_databases_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexRequest) ProtoMessage() {}

func (x *CreateIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexRequest.ProtoReflect.Descriptor instead.
func (*CreateIndexRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{11}
}

func (x *CreateIndexRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *CreateIndexRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *CreateIndexRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateIndexRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateIndexRequest) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateIndexRequest) GetOrders() []string {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Index struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Attributes    []string               `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Orders        []string               `protobuf:"bytes,4,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_server_v1_databases_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_databases_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_server_v1_databases_proto_rawDescGZIP(), []int{12}
}

func (x *Index) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Index) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Index) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Index) GetOrders() []string {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_server_v1_databases_proto protoreflect.FileDescriptor

const file_server_v1_databases_proto_rawDesc = "" +
	"\n" +
	"\x19server/v1/databases.proto\x12\x0ffleet.server.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15shared/v1/authz.proto\x1a\x16shared/v1/common.proto\";\n" +
	"\x15CreateDatabaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"$\n" +
	"\x12GetDatabaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x87\x01\n" +
	"\x15ListDatabasesResponse\x127\n" +
	"\tdatabases\x18\x01 \x03(\v2\x19.fleet.server.v1.DatabaseR\tdatabases\x125\n" +
	"\x04meta\x18\x02 \x01(\v2!.fleet.shared.v1.ListResponseMetaR\x04meta\"\xa4\x01\n" +
	"\bDatabase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x80\x01\n" +
	"\x17CreateCollectionRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\"\x8f\x01\n" +
	"\x16ListCollectionsRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12\x18\n" +
	"\aqueries\x18\x02 \x03(\tR\aqueries\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\\\n" +
	"\x14GetCollectionRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\"\x8f\x01\n" +
	"\x17ListCollectionsResponse\x12=\n" +
	"\vcollections\x18\x01 \x03(\v2\x1b.fleet.server.v1.CollectionR\vcollections\x125\n" +
	"\x04meta\x18\x02 \x01(\v2!.fleet.shared.v1.ListResponseMetaR\x04meta\"\xd7\x02\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdatabase_id\x18\x02 \x01(\tR\n" +
	"databaseId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x12:\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2\x1a.fleet.server.v1.AttributeR\n" +
	"attributes\x120\n" +
	"\aindexes\x18\x06 \x03(\v2\x16.fleet.server.v1.IndexR\aindexes\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xef\x01\n" +
	"\x16CreateAttributeRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x05R\x04size\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\x12\x14\n" +
	"\x05array\x18\a \x01(\bR\x05array\x12#\n" +
	"\rdefault_value\x18\b \x01(\tR\fdefaultValue\"\xac\x01\n" +
	"\tAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x14\n" +
	"\x05array\x18\x06 \x01(\bR\x05array\x12#\n" +
	"\rdefault_value\x18\a \x01(\tR\fdefaultValue\"\xb6\x01\n" +
	"\x12CreateIndexRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"attributes\x18\x05 \x03(\tR\n" +
	"attributes\x12\x16\n" +
	"\x06orders\x18\x06 \x03(\tR\x06orders\"c\n" +
	"\x05Index\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"attributes\x18\x03 \x03(\tR\n" +
	"attributes\x12\x16\n" +
	"\x06orders\x18\x04 \x03(\tR\x06orders2\xa8\v\n" +
	"\x10DatabasesService\x12t\n" +
	"\x0eCreateDatabase\x12&.fleet.server.v1.CreateDatabaseRequest\x1a\x19.fleet.server.v1.Database\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/server/databases\x12s\n" +
	"\rListDatabases\x12\x1c.fleet.shared.v1.ListRequest\x1a&.fleet.server.v1.ListDatabasesResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/server/databases\x12p\n" +
	"\vGetDatabase\x12#.fleet.server.v1.GetDatabaseRequest\x1a\x19.fleet.server.v1.Database\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/server/databases/{id}\x12p\n" +
	"\x0eDeleteDatabase\x12#.fleet.server.v1.GetDatabaseRequest\x1a\x16.fleet.shared.v1.Empty\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/server/databases/{id}\x12\x94\x01\n" +
	"\x10CreateCollection\x12(.fleet.server.v1.CreateCollectionRequest\x1a\x1b.fleet.server.v1.Collection\"9\x82\xd3\xe4\x93\x023:\x01*\"./v1/server/databases/{database_id}/collections\x12\x9c\x01\n" +
	"\x0fListCollections\x12'.fleet.server.v1.ListCollectionsRequest\x1a(.fleet.server.v1.ListCollectionsResponse\"6\x82\xd3\xe4\x93\x020\x12./v1/server/databases/{database_id}/collections\x12\x9b\x01\n" +
	"\rGetCollection\x12%.fleet.server.v1.GetCollectionRequest\x1a\x1b.fleet.server.v1.Collection\"F\x82\xd3\xe4\x93\x02@\x12>/v1/server/databases/{database_id}/collections/{collection_id}\x12\x99\x01\n" +
	"\x10DeleteCollection\x12%.fleet.server.v1.GetCollectionRequest\x1a\x16.fleet.shared.v1.Empty\"F\x82\xd3\xe4\x93\x02@*>/v1/server/databases/{database_id}/collections/{collection_id}\x12\xac\x01\n" +
	"\x0fCreateAttribute\x12'.fleet.server.v1.CreateAttributeRequest\x1a\x1a.fleet.server.v1.Attribute\"T\x82\xd3\xe4\x93\x02N:\x01*\"I/v1/server/databases/{database_id}/collections/{collection_id}/attributes\x12\x9d\x01\n" +
	"\vCreateIndex\x12#.fleet.server.v1.CreateIndexRequest\x1a\x16.fleet.server.v1.Index\"Q\x82\xd3\xe4\x93\x02K:\x01*\"F/v1/server/databases/{database_id}/collections/{collection_id}/indexes\x1a\x06\x92\xb2\x19\x02\b\x04B:Z8github.com/deeploop-ai/fleet/genproto/server/v1;serverv1b\x06proto3"

var (
	file_server_v1_databases_proto_rawDescOnce sync.Once
	file_server_v1_databases_proto_rawDescData []byte
)

func file_server_v1_databases_proto_rawDescGZIP() []byte {
	file_server_v1_databases_proto_rawDescOnce.Do(func() {
		file_server_v1_databases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_databases_proto_rawDesc), len(file_server_v1_databases_proto_rawDesc)))
	})
	return file_server_v1_databases_proto_rawDescData
}

var file_server_v1_databases_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_server_v1_databases_proto_goTypes = []any{
	(*CreateDatabaseRequest)(nil),   // 0: fleet.server.v1.CreateDatabaseRequest
	(*GetDatabaseRequest)(nil),      // 1: fleet.server.v1.GetDatabaseRequest
	(*ListDatabasesResponse)(nil),   // 2: fleet.server.v1.ListDatabasesResponse
	(*Database)(nil),                // 3: fleet.server.v1.Database
	(*CreateCollectionRequest)(nil), // 4: fleet.server.v1.CreateCollectionRequest
	(*ListCollectionsRequest)(nil),  // 5: fleet.server.v1.ListCollectionsRequest
	(*GetCollectionRequest)(nil),    // 6: fleet.server.v1.GetCollectionRequest
	(*ListCollectionsResponse)(nil), // 7: fleet.server.v1.ListCollectionsResponse
	(*Collection)(nil),              // 8: fleet.server.v1.Collection
	(*CreateAttributeRequest)(nil),  // 9: fleet.server.v1.CreateAttributeRequest
	(*Attribute)(nil),               // 10: fleet.server.v1.Attribute
	(*CreateIndexRequest)(nil),      // 11: fleet.server.v1.CreateIndexRequest
	(*Index)(nil),                   // 12: fleet.server.v1.Index
	(*v1.ListResponseMeta)(nil),     // 13: fleet.shared.v1.ListResponseMeta
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
	(*v1.ListRequest)(nil),          // 15: fleet.shared.v1.ListRequest
	(*v1.Empty)(nil),                // 16: fleet.shared.v1.Empty
}
var file_server_v1_databases_proto_depIdxs = []int32{
	3,  // 0: fleet.server.v1.ListDatabasesResponse.databases:type_name -> fleet.server.v1.Database
	13, // 1: fleet.server.v1.ListDatabasesResponse.meta:type_name -> fleet.shared.v1.ListResponseMeta
	14, // 2: fleet.server.v1.Database.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: fleet.server.v1.Database.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 4: fleet.server.v1.ListCollectionsResponse.collections:type_name -> fleet.server.v1.Collection
	13, // 5: fleet.server.v1.ListCollectionsResponse.meta:type_name -> fleet.shared.v1.ListResponseMeta
	10, // 6: fleet.server.v1.Collection.attributes:type_name -> fleet.server.v1.Attribute
	12, // 7: fleet.server.v1.Collection.indexes:type_name -> fleet.server.v1.Index
	14, // 8: fleet.server.v1.Collection.created_at:type_name -> google.protobuf.Timestamp
	14, // 9: fleet.server.v1.Collection.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 10: fleet.server.v1.DatabasesService.CreateDatabase:input_type -> fleet.server.v1.CreateDatabaseRequest
	15, // 11: fleet.server.v1.DatabasesService.ListDatabases:input_type -> fleet.shared.v1.ListRequest
	1,  // 12: fleet.server.v1.DatabasesService.GetDatabase:input_type -> fleet.server.v1.GetDatabaseRequest
	1,  // 13: fleet.server.v1.DatabasesService.DeleteDatabase:input_type -> fleet.server.v1.GetDatabaseRequest
	4,  // 14: fleet.server.v1.DatabasesService.CreateCollection:input_type -> fleet.server.v1.CreateCollectionRequest
	5,  // 15: fleet.server.v1.DatabasesService.ListCollections:input_type -> fleet.server.v1.ListCollectionsRequest
	6,  // 16: fleet.server.v1.DatabasesService.GetCollection:input_type -> fleet.server.v1.GetCollectionRequest
	6,  // 17: fleet.server.v1.DatabasesService.DeleteCollection:input_type -> fleet.server.v1.GetCollectionRequest
	9,  // 18: fleet.server.v1.DatabasesService.CreateAttribute:input_type -> fleet.server.v1.CreateAttributeRequest
	11, // 19: fleet.server.v1.DatabasesService.CreateIndex:input_type -> fleet.server.v1.CreateIndexRequest
	3,  // 20: fleet.server.v1.DatabasesService.CreateDatabase:output_type -> fleet.server.v1.Database
	2,  // 21: fleet.server.v1.DatabasesService.ListDatabases:output_type -> fleet.server.v1.ListDatabasesResponse
	3,  // 22: fleet.server.v1.DatabasesService.GetDatabase:output_type -> fleet.server.v1.Database
	16, // 23: fleet.server.v1.DatabasesService.DeleteDatabase:output_type -> fleet.shared.v1.Empty
	8,  // 24: fleet.server.v1.DatabasesService.CreateCollection:output_type -> fleet.server.v1.Collection
	7,  // 25: fleet.server.v1.DatabasesService.ListCollections:output_type -> fleet.server.v1.ListCollectionsResponse
	8,  // 26: fleet.server.v1.DatabasesService.GetCollection:output_type -> fleet.server.v1.Collection
	16, // 27: fleet.server.v1.DatabasesService.DeleteCollection:output_type -> fleet.shared.v1.Empty
	10, // 28: fleet.server.v1.DatabasesService.CreateAttribute:output_type -> fleet.server.v1.Attribute
	12, // 29: fleet.server.v1.DatabasesService.CreateIndex:output_type -> fleet.server.v1.Index
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_server_v1_databases_proto_init() }
func file_server_v1_databases_proto_init() {
	if File_server_v1_databases_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_databases_proto_rawDesc), len(file_server_v1_databases_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_databases_proto_goTypes,
		DependencyIndexes: file_server_v1_databases_proto_depIdxs,
		MessageInfos:      file_server_v1_databases_proto_msgTypes,
	}.Build()
	File_server_v1_databases_proto = out.File
	file_server_v1_databases_proto_goTypes = nil
	file_server_v1_databases_proto_depIdxs = nil
}
