// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: server/v1/teams.proto

package serverv1

import (
	v1 "github.com/deeploop-ai/fleet/genproto/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_server_v1_teams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeamRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_server_v1_teams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{1}
}

func (x *GetTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsResponse) Reset() {
	*x = ListTeamsResponse{}
	mi := &file_server_v1_teams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsResponse) ProtoMessage() {}

func (x *ListTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{2}
}

func (x *ListTeamsResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *ListTeamsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_server_v1_teams_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_teams_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_server_v1_teams_proto_rawDescGZIP(), []int{3}
}

func (x *Team) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Team) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Team) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Team) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_server_v1_teams_proto protoreflect.FileDescriptor

const file_server_v1_teams_proto_rawDesc = "" +
	"\n" +
	"\x15server/v1/teams.proto\x12\x0ffleet.server.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15shared/v1/authz.proto\x1a\x16shared/v1/common.proto\"I\n" +
	"\x11CreateTeamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\" \n" +
	"\x0eGetTeamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"w\n" +
	"\x11ListTeamsResponse\x12+\n" +
	"\x05teams\x18\x01 \x03(\v2\x15.fleet.server.v1.TeamR\x05teams\x125\n" +
	"\x04meta\x18\x02 \x01(\v2!.fleet.shared.v1.ListResponseMetaR\x04meta\"\xd8\x01\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xad\x03\n" +
	"\fTeamsService\x12d\n" +
	"\n" +
	"CreateTeam\x12\".fleet.server.v1.CreateTeamRequest\x1a\x15.fleet.server.v1.Team\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/server/teams\x12g\n" +
	"\tListTeams\x12\x1c.fleet.shared.v1.ListRequest\x1a\".fleet.server.v1.ListTeamsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/server/teams\x12`\n" +
	"\aGetTeam\x12\x1f.fleet.server.v1.GetTeamRequest\x1a\x15.fleet.server.v1.Team\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/server/teams/{id}\x12d\n" +
	"\n" +
	"DeleteTeam\x12\x1f.fleet.server.v1.GetTeamRequest\x1a\x16.fleet.shared.v1.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/server/teams/{id}\x1a\x06\x92\xb2\x19\x02\b\x04B:Z8github.com/deeploop-ai/fleet/genproto/server/v1;serverv1b\x06proto3"

var (
	file_server_v1_teams_proto_rawDescOnce sync.Once
	file_server_v1_teams_proto_rawDescData []byte
)

func file_server_v1_teams_proto_rawDescGZIP() []byte {
	file_server_v1_teams_proto_rawDescOnce.Do(func() {
		file_server_v1_teams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_teams_proto_rawDesc), len(file_server_v1_teams_proto_rawDesc)))
	})
	return file_server_v1_teams_proto_rawDescData
}

var file_server_v1_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_server_v1_teams_proto_goTypes = []any{
	(*CreateTeamRequest)(nil),     // 0: fleet.server.v1.CreateTeamRequest
	(*GetTeamRequest)(nil),        // 1: fleet.server.v1.GetTeamRequest
	(*ListTeamsResponse)(nil),     // 2: fleet.server.v1.ListTeamsResponse
	(*Team)(nil),                  // 3: fleet.server.v1.Team
	(*v1.ListResponseMeta)(nil),   // 4: fleet.shared.v1.ListResponseMeta
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*v1.ListRequest)(nil),        // 6: fleet.shared.v1.ListRequest
	(*v1.Empty)(nil),              // 7: fleet.shared.v1.Empty
}
var file_server_v1_teams_proto_depIdxs = []int32{
	3, // 0: fleet.server.v1.ListTeamsResponse.teams:type_name -> fleet.server.v1.Team
	4, // 1: fleet.server.v1.ListTeamsResponse.meta:type_name -> fleet.shared.v1.ListResponseMeta
	5, // 2: fleet.server.v1.Team.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: fleet.server.v1.Team.updated_at:type_name -> google.protobuf.Timestamp
	0, // 4: fleet.server.v1.TeamsService.CreateTeam:input_type -> fleet.server.v1.CreateTeamRequest
	6, // 5: fleet.server.v1.TeamsService.ListTeams:input_type -> fleet.shared.v1.ListRequest
	1, // 6: fleet.server.v1.TeamsService.GetTeam:input_type -> fleet.server.v1.GetTeamRequest
	1, // 7: fleet.server.v1.TeamsService.DeleteTeam:input_type -> fleet.server.v1.GetTeamRequest
	3, // 8: fleet.server.v1.TeamsService.CreateTeam:output_type -> fleet.server.v1.Team
	2, // 9: fleet.server.v1.TeamsService.ListTeams:output_type -> fleet.server.v1.ListTeamsResponse
	3, // 10: fleet.server.v1.TeamsService.GetTeam:output_type -> fleet.server.v1.Team
	7, // 11: fleet.server.v1.TeamsService.DeleteTeam:output_type -> fleet.shared.v1.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_server_v1_teams_proto_init() }
func file_server_v1_teams_proto_init() {
	if File_server_v1_teams_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_teams_proto_rawDesc), len(file_server_v1_teams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_teams_proto_goTypes,
		DependencyIndexes: file_server_v1_teams_proto_depIdxs,
		MessageInfos:      file_server_v1_teams_proto_msgTypes,
	}.Build()
	File_server_v1_teams_proto = out.File
	file_server_v1_teams_proto_goTypes = nil
	file_server_v1_teams_proto_depIdxs = nil
}
