// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Security      *Security              `protobuf:"bytes,2,opt,name=security,proto3" json:"security,omitempty"`
	Data          *Data                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Storage       *Storage               `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage,omitempty"`
	Functions     *Functions             `protobuf:"bytes,5,opt,name=functions,proto3" json:"functions,omitempty"`
	Telemetry     *Telemetry             `protobuf:"bytes,6,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppConfig) Reset() {
	*x = AppConfig{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppConfig) ProtoMessage() {}

func (x *AppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppConfig.ProtoReflect.Descriptor instead.
func (*AppConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *AppConfig) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *AppConfig) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *AppConfig) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppConfig) GetStorage() *Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *AppConfig) GetFunctions() *Functions {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *AppConfig) GetTelemetry() *Telemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *GRPC                  `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Http          *Http                  `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	Metrics       *Http                  `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetGrpc() *GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetHttp() *Http {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetMetrics() *Http {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPC) Reset() {
	*x = GRPC{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPC) ProtoMessage() {}

func (x *GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPC.ProtoReflect.Descriptor instead.
func (*GRPC) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *GRPC) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type Http struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Cors          *Http_Cors             `protobuf:"bytes,3,opt,name=cors,proto3" json:"cors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Http) Reset() {
	*x = Http{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http) ProtoMessage() {}

func (x *Http) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Http.ProtoReflect.Descriptor instead.
func (*Http) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *Http) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Http) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *Http) GetCors() *Http_Cors {
	if x != nil {
		return x.Cors
	}
	return nil
}

type Security struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           *Security_Jwt          `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	ApiKey        *Security_ApiKey       `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security) Reset() {
	*x = Security{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security.ProtoReflect.Descriptor instead.
func (*Security) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *Security) GetJwt() *Security_Jwt {
	if x != nil {
		return x.Jwt
	}
	return nil
}

func (x *Security) GetApiKey() *Security_ApiKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Debug         bool                   `protobuf:"varint,2,opt,name=debug,proto3" json:"debug,omitempty"`
	Pool          *Database_Pool         `protobuf:"bytes,3,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Database) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *Database) GetPool() *Database_Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

type Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redis) Reset() {
	*x = Redis{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redis) ProtoMessage() {}

func (x *Redis) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redis.ProtoReflect.Descriptor instead.
func (*Redis) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Database              `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Redis                 `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *Data) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Storage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	S3            *Storage_S3            `protobuf:"bytes,2,opt,name=s3,proto3" json:"s3,omitempty"`
	Local         *Storage_Local         `protobuf:"bytes,3,opt,name=local,proto3" json:"local,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Storage) Reset() {
	*x = Storage{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *Storage) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Storage) GetS3() *Storage_S3 {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *Storage) GetLocal() *Storage_Local {
	if x != nil {
		return x.Local
	}
	return nil
}

type Functions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executor      string                 `protobuf:"bytes,1,opt,name=executor,proto3" json:"executor,omitempty"`
	Docker        *Functions_Docker      `protobuf:"bytes,2,opt,name=docker,proto3" json:"docker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Functions) Reset() {
	*x = Functions{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Functions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Functions) ProtoMessage() {}

func (x *Functions) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Functions.ProtoReflect.Descriptor instead.
func (*Functions) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

func (x *Functions) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *Functions) GetDocker() *Functions_Docker {
	if x != nil {
		return x.Docker
	}
	return nil
}

type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	OtlpEndpoint  string                 `protobuf:"bytes,2,opt,name=otlp_endpoint,json=otlpEndpoint,proto3" json:"otlp_endpoint,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10}
}

func (x *Telemetry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Telemetry) GetOtlpEndpoint() string {
	if x != nil {
		return x.OtlpEndpoint
	}
	return ""
}

func (x *Telemetry) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type Http_Cors struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AllowOrigins     []string               `protobuf:"bytes,1,rep,name=allow_origins,json=allowOrigins,proto3" json:"allow_origins,omitempty"`
	AllowMethods     []string               `protobuf:"bytes,2,rep,name=allow_methods,json=allowMethods,proto3" json:"allow_methods,omitempty"`
	AllowHeaders     []string               `protobuf:"bytes,3,rep,name=allow_headers,json=allowHeaders,proto3" json:"allow_headers,omitempty"`
	ExposeHeaders    []string               `protobuf:"bytes,4,rep,name=expose_headers,json=exposeHeaders,proto3" json:"expose_headers,omitempty"`
	AllowCredentials bool                   `protobuf:"varint,5,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	MaxAge           int32                  `protobuf:"varint,6,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Http_Cors) Reset() {
	*x = Http_Cors{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Http_Cors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http_Cors) ProtoMessage() {}

func (x *Http_Cors) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Http_Cors.ProtoReflect.Descriptor instead.
func (*Http_Cors) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Http_Cors) GetAllowOrigins() []string {
	if x != nil {
		return x.AllowOrigins
	}
	return nil
}

func (x *Http_Cors) GetAllowMethods() []string {
	if x != nil {
		return x.AllowMethods
	}
	return nil
}

func (x *Http_Cors) GetAllowHeaders() []string {
	if x != nil {
		return x.AllowHeaders
	}
	return nil
}

func (x *Http_Cors) GetExposeHeaders() []string {
	if x != nil {
		return x.ExposeHeaders
	}
	return nil
}

func (x *Http_Cors) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

func (x *Http_Cors) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

type Security_Jwt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	AccessTtl     string                 `protobuf:"bytes,2,opt,name=access_ttl,json=accessTtl,proto3" json:"access_ttl,omitempty"`
	RefreshTtl    string                 `protobuf:"bytes,3,opt,name=refresh_ttl,json=refreshTtl,proto3" json:"refresh_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_Jwt) Reset() {
	*x = Security_Jwt{}
	mi := &file_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_Jwt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_Jwt) ProtoMessage() {}

func (x *Security_Jwt) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_Jwt.ProtoReflect.Descriptor instead.
func (*Security_Jwt) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Security_Jwt) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Security_Jwt) GetAccessTtl() string {
	if x != nil {
		return x.AccessTtl
	}
	return ""
}

func (x *Security_Jwt) GetRefreshTtl() string {
	if x != nil {
		return x.RefreshTtl
	}
	return ""
}

type Security_ApiKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_ApiKey) Reset() {
	*x = Security_ApiKey{}
	mi := &file_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_ApiKey) ProtoMessage() {}

func (x *Security_ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_ApiKey.ProtoReflect.Descriptor instead.
func (*Security_ApiKey) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Security_ApiKey) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

type Database_Pool struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxIdleConns    int32                  `protobuf:"varint,1,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	MaxOpenConns    int32                  `protobuf:"varint,2,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	ConnMaxLifetime string                 `protobuf:"bytes,3,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	ConnMaxIdleTime string                 `protobuf:"bytes,4,opt,name=conn_max_idle_time,json=connMaxIdleTime,proto3" json:"conn_max_idle_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Database_Pool) Reset() {
	*x = Database_Pool{}
	mi := &file_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database_Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database_Pool) ProtoMessage() {}

func (x *Database_Pool) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database_Pool.ProtoReflect.Descriptor instead.
func (*Database_Pool) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Database_Pool) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Database_Pool) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Database_Pool) GetConnMaxLifetime() string {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return ""
}

func (x *Database_Pool) GetConnMaxIdleTime() string {
	if x != nil {
		return x.ConnMaxIdleTime
	}
	return ""
}

type Storage_S3 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoint        string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Region          string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Bucket          string                 `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	AccessKeyId     string                 `protobuf:"bytes,4,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,5,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	UseSsl          bool                   `protobuf:"varint,6,opt,name=use_ssl,json=useSsl,proto3" json:"use_ssl,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Storage_S3) Reset() {
	*x = Storage_S3{}
	mi := &file_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage_S3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage_S3) ProtoMessage() {}

func (x *Storage_S3) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage_S3.ProtoReflect.Descriptor instead.
func (*Storage_S3) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Storage_S3) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Storage_S3) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Storage_S3) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Storage_S3) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *Storage_S3) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *Storage_S3) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

type Storage_Local struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Storage_Local) Reset() {
	*x = Storage_Local{}
	mi := &file_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage_Local) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage_Local) ProtoMessage() {}

func (x *Storage_Local) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage_Local.ProtoReflect.Descriptor instead.
func (*Storage_Local) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8, 1}
}

func (x *Storage_Local) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Functions_Docker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Registry      string                 `protobuf:"bytes,3,opt,name=registry,proto3" json:"registry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Functions_Docker) Reset() {
	*x = Functions_Docker{}
	mi := &file_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Functions_Docker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Functions_Docker) ProtoMessage() {}

func (x *Functions_Docker) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Functions_Docker.ProtoReflect.Descriptor instead.
func (*Functions_Docker) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9, 0}
}

func (x *Functions_Docker) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Functions_Docker) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Functions_Docker) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x12orionid.api.config\"\xd8\x02\n" +
	"\tAppConfig\x122\n" +
	"\x06server\x18\x01 \x01(\v2\x1a.orionid.api.config.ServerR\x06server\x128\n" +
	"\bsecurity\x18\x02 \x01(\v2\x1c.orionid.api.config.SecurityR\bsecurity\x12,\n" +
	"\x04data\x18\x03 \x01(\v2\x18.orionid.api.config.DataR\x04data\x125\n" +
	"\astorage\x18\x04 \x01(\v2\x1b.orionid.api.config.StorageR\astorage\x12;\n" +
	"\tfunctions\x18\x05 \x01(\v2\x1d.orionid.api.config.FunctionsR\tfunctions\x12;\n" +
	"\ttelemetry\x18\x06 \x01(\v2\x1d.orionid.api.config.TelemetryR\ttelemetry\"\x98\x01\n" +
	"\x06Server\x12,\n" +
	"\x04grpc\x18\x01 \x01(\v2\x18.orionid.api.config.GRPCR\x04grpc\x12,\n" +
	"\x04http\x18\x02 \x01(\v2\x18.orionid.api.config.HttpR\x04http\x122\n" +
	"\ametrics\x18\x03 \x01(\v2\x18.orionid.api.config.HttpR\ametrics\"4\n" +
	"\x04GRPC\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\"\xcc\x02\n" +
	"\x04Http\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\x121\n" +
	"\x04cors\x18\x03 \x01(\v2\x1d.orionid.api.config.Http.CorsR\x04cors\x1a\xe2\x01\n" +
	"\x04Cors\x12#\n" +
	"\rallow_origins\x18\x01 \x03(\tR\fallowOrigins\x12#\n" +
	"\rallow_methods\x18\x02 \x03(\tR\fallowMethods\x12#\n" +
	"\rallow_headers\x18\x03 \x03(\tR\fallowHeaders\x12%\n" +
	"\x0eexpose_headers\x18\x04 \x03(\tR\rexposeHeaders\x12+\n" +
	"\x11allow_credentials\x18\x05 \x01(\bR\x10allowCredentials\x12\x17\n" +
	"\amax_age\x18\x06 \x01(\x05R\x06maxAge\"\xfd\x01\n" +
	"\bSecurity\x122\n" +
	"\x03jwt\x18\x01 \x01(\v2 .orionid.api.config.Security.JwtR\x03jwt\x12<\n" +
	"\aapi_key\x18\x02 \x01(\v2#.orionid.api.config.Security.ApiKeyR\x06apiKey\x1a]\n" +
	"\x03Jwt\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x1d\n" +
	"\n" +
	"access_ttl\x18\x02 \x01(\tR\taccessTtl\x12\x1f\n" +
	"\vrefresh_ttl\x18\x03 \x01(\tR\n" +
	"refreshTtl\x1a \n" +
	"\x06ApiKey\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\"\x9d\x02\n" +
	"\bDatabase\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05debug\x18\x02 \x01(\bR\x05debug\x125\n" +
	"\x04pool\x18\x03 \x01(\v2!.orionid.api.config.Database.PoolR\x04pool\x1a\xab\x01\n" +
	"\x04Pool\x12$\n" +
	"\x0emax_idle_conns\x18\x01 \x01(\x05R\fmaxIdleConns\x12$\n" +
	"\x0emax_open_conns\x18\x02 \x01(\x05R\fmaxOpenConns\x12*\n" +
	"\x11conn_max_lifetime\x18\x03 \x01(\tR\x0fconnMaxLifetime\x12+\n" +
	"\x12conn_max_idle_time\x18\x04 \x01(\tR\x0fconnMaxIdleTime\"G\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\"q\n" +
	"\x04Data\x128\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1c.orionid.api.config.DatabaseR\bdatabase\x12/\n" +
	"\x05redis\x18\x02 \x01(\v2\x19.orionid.api.config.RedisR\x05redis\"\xe7\x02\n" +
	"\aStorage\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12.\n" +
	"\x02s3\x18\x02 \x01(\v2\x1e.orionid.api.config.Storage.S3R\x02s3\x127\n" +
	"\x05local\x18\x03 \x01(\v2!.orionid.api.config.Storage.LocalR\x05local\x1a\xb9\x01\n" +
	"\x02S3\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x12\"\n" +
	"\raccess_key_id\x18\x04 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x05 \x01(\tR\x0fsecretAccessKey\x12\x17\n" +
	"\ause_ssl\x18\x06 \x01(\bR\x06useSsl\x1a\x1b\n" +
	"\x05Local\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xb9\x01\n" +
	"\tFunctions\x12\x1a\n" +
	"\bexecutor\x18\x01 \x01(\tR\bexecutor\x12<\n" +
	"\x06docker\x18\x02 \x01(\v2$.orionid.api.config.Functions.DockerR\x06docker\x1aR\n" +
	"\x06Docker\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x1a\n" +
	"\bregistry\x18\x03 \x01(\tR\bregistry\"m\n" +
	"\tTelemetry\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12#\n" +
	"\rotlp_endpoint\x18\x02 \x01(\tR\fotlpEndpoint\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceNameB4Z2github.com/deeploop-ai/orionid/internal/pkg/configb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_config_proto_goTypes = []any{
	(*AppConfig)(nil),        // 0: orionid.api.config.AppConfig
	(*Server)(nil),           // 1: orionid.api.config.Server
	(*GRPC)(nil),             // 2: orionid.api.config.GRPC
	(*Http)(nil),             // 3: orionid.api.config.Http
	(*Security)(nil),         // 4: orionid.api.config.Security
	(*Database)(nil),         // 5: orionid.api.config.Database
	(*Redis)(nil),            // 6: orionid.api.config.Redis
	(*Data)(nil),             // 7: orionid.api.config.Data
	(*Storage)(nil),          // 8: orionid.api.config.Storage
	(*Functions)(nil),        // 9: orionid.api.config.Functions
	(*Telemetry)(nil),        // 10: orionid.api.config.Telemetry
	(*Http_Cors)(nil),        // 11: orionid.api.config.Http.Cors
	(*Security_Jwt)(nil),     // 12: orionid.api.config.Security.Jwt
	(*Security_ApiKey)(nil),  // 13: orionid.api.config.Security.ApiKey
	(*Database_Pool)(nil),    // 14: orionid.api.config.Database.Pool
	(*Storage_S3)(nil),       // 15: orionid.api.config.Storage.S3
	(*Storage_Local)(nil),    // 16: orionid.api.config.Storage.Local
	(*Functions_Docker)(nil), // 17: orionid.api.config.Functions.Docker
}
var file_config_proto_depIdxs = []int32{
	1,  // 0: orionid.api.config.AppConfig.server:type_name -> orionid.api.config.Server
	4,  // 1: orionid.api.config.AppConfig.security:type_name -> orionid.api.config.Security
	7,  // 2: orionid.api.config.AppConfig.data:type_name -> orionid.api.config.Data
	8,  // 3: orionid.api.config.AppConfig.storage:type_name -> orionid.api.config.Storage
	9,  // 4: orionid.api.config.AppConfig.functions:type_name -> orionid.api.config.Functions
	10, // 5: orionid.api.config.AppConfig.telemetry:type_name -> orionid.api.config.Telemetry
	2,  // 6: orionid.api.config.Server.grpc:type_name -> orionid.api.config.GRPC
	3,  // 7: orionid.api.config.Server.http:type_name -> orionid.api.config.Http
	3,  // 8: orionid.api.config.Server.metrics:type_name -> orionid.api.config.Http
	11, // 9: orionid.api.config.Http.cors:type_name -> orionid.api.config.Http.Cors
	12, // 10: orionid.api.config.Security.jwt:type_name -> orionid.api.config.Security.Jwt
	13, // 11: orionid.api.config.Security.api_key:type_name -> orionid.api.config.Security.ApiKey
	14, // 12: orionid.api.config.Database.pool:type_name -> orionid.api.config.Database.Pool
	5,  // 13: orionid.api.config.Data.database:type_name -> orionid.api.config.Database
	6,  // 14: orionid.api.config.Data.redis:type_name -> orionid.api.config.Redis
	15, // 15: orionid.api.config.Storage.s3:type_name -> orionid.api.config.Storage.S3
	16, // 16: orionid.api.config.Storage.local:type_name -> orionid.api.config.Storage.Local
	17, // 17: orionid.api.config.Functions.docker:type_name -> orionid.api.config.Functions.Docker
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
