// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/deeploop-ai/fleet/internal/api/clientgrpc"
	"github.com/deeploop-ai/fleet/internal/api/consolegrpc"
	"github.com/deeploop-ai/fleet/internal/api/servergrpc"
	"github.com/deeploop-ai/fleet/internal/api/serverhttp"
	"github.com/deeploop-ai/fleet/internal/app/client"
	"github.com/deeploop-ai/fleet/internal/app/console"
	"github.com/deeploop-ai/fleet/internal/app/server"
	storage2 "github.com/deeploop-ai/fleet/internal/app/storage"
	"github.com/deeploop-ai/fleet/internal/infra/auth"
	"github.com/deeploop-ai/fleet/internal/infra/bun/bunrepo"
	"github.com/deeploop-ai/fleet/internal/infra/clients"
	"github.com/deeploop-ai/fleet/internal/infra/documentdb"
	server2 "github.com/deeploop-ai/fleet/internal/infra/server"
	"github.com/deeploop-ai/fleet/internal/infra/storage"
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx/boot"
)

// Injectors from wire.go:

func wireBootstrap(app lynx.Lynx) (*boot.Bootstrap, func(), error) {
	onStartHooks := NewOnStarts()
	onStopHooks := NewOnStops()
	appConfig, err := NewAppConfig(app)
	if err != nil {
		return nil, nil, err
	}
	dataClients, cleanup, err := clients.NewDataClients(appConfig)
	if err != nil {
		return nil, nil, err
	}
	database := clients.NewDatabase(dataClients)
	apiKeyRepository := bunrepo.NewAPIKeyRepository(database)
	consoleAdminRepository := bunrepo.NewConsoleAdminRepository(database)
	consoleAdminProjectRepository := bunrepo.NewConsoleAdminProjectRepository(database)
	documentDB := documentdb.NewPostgresDocumentDB(database)
	validator := auth.NewValidator(appConfig, apiKeyRepository, consoleAdminRepository, consoleAdminProjectRepository, documentDB)
	repository := bunrepo.NewAuditRepository(database)
	projectsRepository := bunrepo.NewProjectRepository(database)
	account := client.NewAccount(appConfig, projectsRepository, documentDB)
	accountService := clientgrpc.NewAccountService(account)
	databases := client.NewDatabases(projectsRepository, documentDB)
	databasesService := clientgrpc.NewDatabasesService(databases)
	healthService := servergrpc.NewHealthService()
	projects := server.NewProjects(projectsRepository, documentDB, database)
	projectsService := servergrpc.NewProjectsService(projects)
	objectStore, err := storage.NewMinioObjectStore(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	storageStorage := storage2.NewStorage(appConfig, projectsRepository, documentDB, objectStore)
	storageService := servergrpc.NewStorageService(storageStorage)
	users := server.NewUsers(projectsRepository, documentDB)
	usersService := servergrpc.NewUsersService(users)
	apiKeys := server.NewAPIKeys(apiKeyRepository)
	apiKeysService := servergrpc.NewAPIKeysService(apiKeys)
	teams := server.NewTeams(projectsRepository, documentDB)
	teamsService := servergrpc.NewTeamsService(teams)
	serverDatabases := server.NewDatabases(projectsRepository, documentDB)
	servergrpcDatabasesService := servergrpc.NewDatabasesService(serverDatabases)
	consoleAuth := console.NewAuth(appConfig, consoleAdminRepository)
	authService := consolegrpc.NewAuthService(consoleAuth)
	grpcServer, err := server2.NewGRPCServer(app, appConfig, validator, repository, accountService, databasesService, healthService, projectsService, storageService, usersService, apiKeysService, teamsService, servergrpcDatabasesService, authService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	fileHandler := serverhttp.NewFileHandler(appConfig, validator, storageStorage)
	grpcGatewayServer, err := server2.NewGRPCGatewayServer(app, appConfig, fileHandler)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	metricsServer, err := server2.NewMetricsServer(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	v := NewComponents(grpcServer, grpcGatewayServer, metricsServer)
	v2 := NewComponentBuilders()
	componentBuilderSetFunc := NewComponentBuilderSetFunc()
	bootstrap := boot.New(onStartHooks, onStopHooks, v, v2, componentBuilderSetFunc)
	return bootstrap, func() {
		cleanup()
	}, nil
}
